export const QUERY_KEYS = {
  ORDER_SUMMARY: "order-summary",
  ORDERS: "orders",
  PRODUCTS: "products",
  INCOMING_SHIPMENTS: "incoming-shipments",
  SHIPMENTS: "shipments",
  PALLETS: "pallets",
  PALLET_PRODUCTS: "pallet-products",
  PALLET: "pallet",
  SUPPLIERS: "suppliers",
  WAREHOUSE_AVAILABLE_LOCATIONS: "warehouse-available-locations",
  WAREHOUSE_UNAVAILABLE_LOCATIONS: "warehouse-unavailable-locations",
  CLERK_USERS: "clerk-users",
  TRACKED_PRODUCTS: "tracked-products",
} as const;
