// Generated by https://quicktype.io

export interface RegisterRequest {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  confirmPassword: string;
  role: string;
  username: string;
}

// Generated by https://quicktype.io

export interface RegisterResponse {
  success: boolean;
  user: User;
}
//
export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  username: string;
  role: string;
}

export interface UserResource {
  publicMetadata: {
    role: string;
  };
  username: string | null;
  primaryEmailAddress: {
    emailAddress: string | null;
  } | null;
}

// Generated by https://quicktype.io

export interface GetUsersResponse {
  success: boolean;
  count: number;
  pagination: Pagination;
  data: GetUsersData[];
}

export interface GetUsersData {
  id: string;
  firstName: null | string;
  lastName: null | string;
  email: string;
  role: string;
  createdAt: number;
  lastSignInAt: number | null;
  username: string;
}

export interface Pagination {
  limit: number;
  offset: number;
  totalPages: null;
  currentPage: number;
  hasNextPage: boolean;
  hasPrevPage: boolean;
}

// Generated by https://quicktype.io

export interface UpdateUserRoleResponse {
  success: boolean;
  message: string;
  data: User;
}

export interface EditUserRole {
  role: string;
  userId: string;
}
