// Generated by https://quicktype.io

export interface GetPalletsResponse {
  success: boolean;
  total: number;
  pages: number;
  currentPage: number;
  data: Pallet[];
}

export interface Pallet {
  id: number;
  pallet_number: string;
  warehouse_location_id: number;
  warehouse_location: string;
  purchase_order_number: string;
  purchase_order_id: number;
  createdAt: Date;
  updatedAt: Date;
  products: PalletProductResponse[];
}

export interface PalletProductResponse {
  id: number;
  PalletProduct: PalletProduct;
}

export interface PalletProduct {
  quantity: number;
  available_quantity: number | null;
}
