// Generated by https://quicktype.io

export interface CreateProductRequest {
  ASIN: string;
  seller_sku: string;
  product_cost: number;
  supplier_id: number;
  supplier_item_number?: string;
}
export interface CreateProductResponse {
  id: number;
  ASIN: string;
  product_cost: string;
  supplier_id: string;
  supplier_item_number: string;
  product_name: string;
  updatedAt: Date;
  createdAt: Date;
}

export interface GetProductsResponse {
  success: boolean;
  total: number;
  pages: number;
  currentPage: number;
  data: Product[];
}

export interface EditProductProps {
  id: number;
  ASIN: string;
  seller_sku?: string | null;
  product_cost?: number | null;
  supplier_id?: number | null;
  supplier_item_number?: string | null;
  upc?: string | null;
  pack_type?: number | null;
}

export interface UpdateProductDGType {
  productId: string;
  dgType: string;
}

export interface GetInventoryProps {
  page?: number;
  limit?: number;
  keyword?: string;
  supplier?: string;
  orderBy?: string;
  orderWay?: string;
}

export interface Product {
  id: number;
  ASIN: string;
  product_image: string;
  product_name: string;
  seller_sku: string;
  warehouse_stock: string;
  FBA_available_inventory: number;
  reserved_quantity: number;
  Inbound_to_FBA: number;
  supplier_id: number;
  supplier_item_number: null | string;
  upc: null | string;
  product_cost: string;
  pack_type: null | string;
  is_active: boolean;
  in_seller_account: boolean;
  createdAt: Date;
  updatedAt: Date;
  supplier_name: string;
}
export interface UpdateProductDGType {
  productId: string;
  dgType: string;
}

export interface SupressedListing {
  ASIN: string;
  seller_sku: string;
  product_name: string;
  reason?: string;
  condition?: number;
  status_change_date?: string;
  issue_description?: string;
}

export interface SupressedListingsResponse {
  success: boolean;
  data: SupressedListing[];
}
