// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface GetPurchaseOrderSummaryResponse {
  success: boolean;
  data: Data;
}

export interface Data {
  order: Order;
  purchaseOrderProducts: PurchaseOrderSummaryProducts[];
}

export interface PurchaseOrderSummaryProducts {
  id: number;
  product_id: number;
  product_name: string;
  in_seller_account: boolean;
  ASIN: string;
  GTIN?: string;
  seller_sku: string;
  supplier_name: string;
  supplier_id: string;
  pack_type: number | null;
  product_image: string;
  supplier_item_number: null;
  product_velocity: number;
  units_sold: number;
  thirty_days_rank: number;
  ninety_days_rank: number;
  lowest_fba_price: number;
  fees: number;
  profit: number;
  roi: string;
  updatedAt: Date;
  product_cost: string;
  purchase_order_product_id: number;
  total_amount: number;
  quantity_purchased: number;
  quantity_available: number;
  quantity_missing: number;
  quantity_received: number;
  reason_id: number | null;
  reason: string;
  upc: string | null;
  expire_date: string | null;
  warehouse_stock: string;
  dg_item: string;
  pallet_quantity?: number;
}

export interface Order {
  status: string;
  order_number: string;
  total_price: string;
  createdAt: Date;
  updatedAt: Date;
  updatedStatusAt: Date | null;
  supplier_name: string;
  notes: string;
  incoming_order_notes: string | null;
  supplier_id: number;
}

export interface TrackedProductsOfTheOrder {
  id: number;
  product_id: number;
  current_rank: number;
  thirty_days_rank: number;
  ninety_days_rank: number;
  units_sold: number;
  product_velocity: number;
  lowest_fba_price: number;
  fees: number;
  profit: number;
  is_active: boolean;
  createdAt: Date;
  updatedAt: Date;
  upc: null;
  in_seller_account: boolean;
  supplier_item_number: string;
  pack_type: null;
  product_name: string;
  ASIN: string;
  seller_sku: string;
  supplier_name: string;
  product_image: string;
  product_cost: string;
}

export interface CustomTrackedProduct extends TrackedProductsOfTheOrder {
  sellable_quantity: number;
  total_amount: number;
  quantity_purchased: number;
  purchase_order_product_id: number;
  purchaseOrderProductId: number;
}

// Generated by https://quicktype.io

export interface IncomingOrderProductUpdates {
  purchase_order_product_id: number;
  product_id: number;
  quantity_received: number;
  quantity_missing: number;
  reason_id: number | null;
  upc: string | null;
  expire_date: string | null;
}
