// Generated by https://quicktype.io

export interface GetPurchaseOrdersResponse {
  success: boolean;
  total: number;
  pages: number;
  currentPage: number;
  data: Order[];
}

export interface Order {
  id: number;
  order_number: string;
  supplier_id: number;
  purchase_order_status_id: number;
  total_price: string;
  notes: string;
  is_active: boolean;
  updatedStatusAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  purchaseOrderStatus: PurchaseOrderStatus;
  purchaseOrderProducts: PurchaseOrderProduct[];
  status: string;
  average_roi: number | null;
  supplier_name: string;
  trackedProducts: TrackedProduct[];
}

interface PurchaseOrderProduct {
  id: number;
  purchase_order_id: number;
  product_id: number;
  unit_price: string;
  product_cost: string;
  total_amount: string;
  profit: string;
  quantity_purchased: number;
  quantity_received: number | null;
  quantity_missing: number;
  quantity_available: number;
  reason_id: number | null;
  notes: null;
  expire_date: null;
  is_active: boolean;
  createdAt: Date;
  updatedAt: Date;
  Product: Product;
  product_name: string;
}

interface Product {
  id: number;
  ASIN: string;
  product_image: string;
  product_name: string;
  seller_sku: string;
  warehouse_stock: string;
  FBA_available_inventory: number;
  reserved_quantity: number;
  Inbound_to_FBA: number;
  supplier_id: number;
  supplier_item_number: null | string;
  upc: null | string;
  product_cost: string;
  pack_type: null | string;
  is_active: boolean;
  in_seller_account: boolean;
  createdAt: Date;
  updatedAt: Date;
}

interface PurchaseOrderStatus {
  id: number;
  description: string;
  createdAt: Date;
  updatedAt: Date;
}

interface TrackedProduct {
  id: number;
  product_id: number;
  current_rank: number;
  thirty_days_rank: number;
  ninety_days_rank: number;
  units_sold: number;
  product_velocity: number;
  lowest_fba_price: number;
  fees: number | null;
  profit: number | null;
  is_active: boolean;
  createdAt: Date;
  updatedAt: Date;
  product_name: string;
  ASIN: string;
  seller_sku: string;
  supplier_name: string;
  product_image: string;
  product_cost: string;
}

// Generated by https://quicktype.io

export interface GetPurchaseOrderSummaryResponse {
  success: boolean;
  data: Data;
}

export interface Data {
  order: Order;
  purchaseOrderProducts: PurchaseOrderSummaryProducts[];
}

export interface PurchaseOrderSummaryProducts {
  id: number;
  product_id: number;
  product_name: string;
  in_seller_account: boolean;
  ASIN: string;
  seller_sku: string;
  supplier_name: string;
  supplier_id: string;
  pack_type: number | null;
  product_image: string;
  supplier_item_number: null;
  product_velocity: number;
  units_sold: number;
  thirty_days_rank: number;
  ninety_days_rank: number;
  lowest_fba_price: number;
  fees: number;
  profit: number;
  roi: string;
  updatedAt: Date;
  product_cost: string;
  purchase_order_product_id: number;
  total_amount: number;
  quantity_purchased: number;
  quantity_available: number;
  quantity_missing: number;
  quantity_received: number;
  reason_id: number | null;
  upc: string | null;
  expire_date: string | null;

  // pallet
  pallet_quantity?: number;
}

export interface Order {
  status: string;
  order_number: string;
  total_price: string;
  createdAt: Date;
  updatedAt: Date;
  updatedStatusAt: Date | null;
  supplier_name: string;
  notes: string;
}

export interface TrackedProductsOfTheOrder {
  id: number;
  product_id: number;
  current_rank: number;
  thirty_days_rank: number;
  ninety_days_rank: number;
  units_sold: number;
  product_velocity: number;
  lowest_fba_price: number;
  fees: number;
  profit: number;
  is_active: boolean;
  createdAt: Date;
  updatedAt: Date;
  upc: null;
  in_seller_account: boolean;
  supplier_item_number: string;
  pack_type: null;
  product_name: string;
  ASIN: string;
  seller_sku: string;
  supplier_name: string;
  product_image: string;
  product_cost: string;
}

export interface CustomTrackedProduct extends TrackedProductsOfTheOrder {
  sellable_quantity: number;
  total_amount: number;
  quantity_purchased: number;
  purchase_order_product_id: number;
  purchaseOrderProductId: number;
}

export interface PurchaseOrderProductsUpdates {
  purchaseOrderProductId: number;
  quantityPurchased: number;
  product_cost: string;
  profit: string;
  unit_price: string;
}

// Generated by https://quicktype.io

export interface IncomingOrderProductUpdates {
  purchase_order_product_id: number;
  product_id: number;
  quantity_received: number;
  quantity_missing: number;
  reason_id: number | null;
  upc: string | null;
  expire_date: string | null;
}
