// Generated by https://quicktype.io

export interface GetShipmentsResponse {
  shipments: Shipment[];
}

export interface Shipment {
  id: number;
  shipment_number: string;
  status: string;
  fba_shipment_id: null;
  createdAt: Date;
  updatedAt: Date;
  PalletProducts: ShipmentPalletProduct[];
}

export interface ShipmentPalletProduct {
  id: number;
  purchaseorderproduct_id: number;
  pallet_id: number;
  quantity: number;
  available_quantity: number;
  createdAt: Date;
  updatedAt: Date;
  OutgoingShipmentProduct: OutgoingShipmentProduct;
}

export interface OutgoingShipmentProduct {
  quantity: number;
}
