// Generated by https://quicktype.io

export interface GetShipmentsResponse {
  shipments: Shipment[];
  total: number;
}

export interface Shipment {
  id: number;
  shipment_number: string;
  status: string;
  fba_shipment_id: null;
  createdAt: Date;
  updatedAt: Date;
  PalletProducts: ShipmentPalletProduct[];
}

export interface ShipmentPalletProduct {
  id: number;
  purchaseorderproduct_id: number;
  pallet_id: number;
  quantity: number;
  available_quantity: number;
  createdAt: Date;
  updatedAt: Date;
  OutgoingShipmentProduct: OutgoingShipmentProduct;
  warehouse_location: string;
}

export interface OutgoingShipmentProduct {
  quantity: number;
}

// Generated by https://quicktype.io

export interface GetShipemntByIDResponse {
  id: number;
  shipment_number: string;
  status: string;
  fba_shipment_id: null;
  createdAt: Date;
  updatedAt: Date;
  PalletProducts: ShipmentPalletProduct[];
}

export interface ShipmentPalletProduct {
  id: number;
  purchaseorderproduct_id: number;
  pallet_id: number;
  quantity: number;
  available_quantity: number;
  createdAt: Date;
  updatedAt: Date;
  Pallet: ShipmentPallet;
  OutgoingShipmentProduct: OutgoingShipmentProduct;
  pallet_number: string;
  product_name: string;
  product_image: string;
  seller_sku: string;
  in_seller_account: boolean | null;
}

export interface OutgoingShipmentProduct {
  quantity: number;
}

export interface ShipmentPallet {
  id: number;
  pallet_number: string;
}
