// Generated by https://quicktype.io

export interface GetTrackedProductsResponse {
  success: boolean;
  total: number;
  pages: number;
  currentPage: number;
  data: TrackedProduct[];
}

export interface TrackedProduct {
  id: number;
  product_id: number;
  current_rank: number;
  thirty_days_rank: number;
  ninety_days_rank: number;
  units_sold: number;
  product_velocity: number;
  lowest_fba_price: number;
  fees: null;
  profit: null;
  is_active: boolean;
  createdAt: Date;
  updatedAt: Date;
  product_name: string;
  ASIN: string;
  seller_sku: string;
  product_cost: string;
  product_image: string;
  supplier_id: null;
  in_seller_account: boolean;
  FBA_available_inventory: number;
  reserved_quantity: number;
  Inbound_to_FBA: number;
  supplier_item_number: null;
  warehouse_stock: string;
  supplier_name: null;
  roi: number;
}
