// Generated by https://quicktype.io

export interface GetWarehouseLocationsResponse {
  success: boolean;
  msg: string;
  data: Location[];
}

export interface Location {
  id: number;
  location: string;
  capacity: number;
  current_capacity: number;
}
