// Generated by https://quicktype.io

export interface GetInventoryResponse {
  success: boolean;
  total: number;
  pages: number;
  currentPage: number;
  data: Product[];
}

export interface Product {
  id: number;
  ASIN: string;
  product_image: string;
  product_name: string;
  seller_sku: string;
  FBA_available_inventory: number;
  reserved_quantity: number;
  Inbound_to_FBA: number;
  supplier_id: number | null;
  supplier_item_number: null;
  upc: null;
  product_cost: string;
  pack_type: null;
  is_active: boolean;
  in_seller_account: boolean;
  createdAt: Date;
  updatedAt: Date;
  supplier: Supplier | null;
}

export interface Supplier {
  supplier_name: string;
}
