import { TrackedProduct } from "../../inventory/tracked-products/interfaces/tracked-product.interface";

// Generated by https://quicktype.io
export interface GetOrdersResponse {
  success: boolean;
  total: number;
  pages: number;
  currentPage: number;
  data: Order[];
}

export interface DeleteOrderResponse {
  success: boolean;
  data: DeleteOrderData;
}

export interface DeleteOrderData {
  id: number;
  order_number: string;
  supplier_id: number;
  purchase_order_status_id: number;
  total_price: string;
  notes: string;
  is_active: boolean;
  updatedStatusAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface Order {
  id: number;
  order_number: string;
  supplier_id: number;
  purchase_order_status_id: number;
  total_price: string;
  notes: null | string;
  is_active: boolean;
  updatedStatusAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  purchaseOrderProducts: PurchaseOrderProduct[];
  purchaseOrderStatus: PurchaseOrderStatus;
  supplier_name: string;
  status: Status;
  average_roi: number | null;
  trackedProducts: TrackedProduct[];
}

export interface PurchaseOrderProduct {
  id: number;
  purchase_order_id: number;
  product_id: number;
  unit_price: string;
  product_cost: string;
  total_amount: string;
  profit: string;
  quantity_purchased: number;
  quantity_received: number | null;
  quantity_missing: number;
  quantity_available: number;
  reason_id: number | null;
  notes: null | string;
  expire_date: Date | null;
  is_active: boolean;
  createdAt: Date;
  updatedAt: Date;
  product_name: string;
}

export interface PurchaseOrderStatus {
  description: Status;
}

export enum Status {
  Arrived = "Arrived",
  Cancelled = "Cancelled",
  Closed = "Closed",
  InTransit = "In transit",
  Pending = "Pending",
  Rejected = "Rejected",
  WaitingForSupplierApproval = "Waiting for supplier approval",
}

// Get Purchase Order By ID Interface

export interface GetOrderByIDResponse {
  success: boolean;
  data: GetOrderByIDData;
}

export interface GetOrderByIDData {
  id: number;
  order_number: string;
  supplier_id: number;
  purchase_order_status_id: number;
  total_price: string;
  notes: null;
  is_active: boolean;
  updatedStatusAt: Date;
  createdAt: Date;
  updatedAt: Date;
  purchaseOrderProducts: PurchaseOrderProduct[];
}

// Get Purchase Order Summary By ID
// Generated by https://quicktype.io

export interface GetPurchaseOrderSummaryResponse {
  success: boolean;
  data: GetPurchaseOrderSummaryData;
}

export interface GetPurchaseOrderSummaryData {
  purchaseOrder: PurchaseOrder;
  trackedProductsOfTheOrder: TrackedProductsOfTheOrder[];
}

export interface PurchaseOrder {
  id: number;
  order_number: string;
  supplier_id: number;
  purchase_order_status_id: number;
  total_price: string;
  notes: string;
  is_active: boolean;
  updatedStatusAt: Date;
  createdAt: Date;
  updatedAt: Date;
  purchaseOrderProducts: PurchaseOrderProduct[];
  purchaseOrderStatus: PurchaseOrderStatus;
  average_roi: null;
}

export interface TrackedProductsOfTheOrder {
  id: number;
  product_id: number;
  current_rank: number;
  thirty_days_rank: number;
  ninety_days_rank: number;
  units_sold: number;
  product_velocity: number;
  lowest_fba_price: number;
  fees: number;
  profit: number;
  is_active: boolean;
  createdAt: Date;
  updatedAt: Date;
  upc: null;
  in_seller_account: boolean;
  supplier_item_number: string;
  pack_type: null;
  product_name: string;
  ASIN: string;
  seller_sku: string;
  supplier_name: string;
  product_image: string;
  product_cost: string;
}

export interface CustomTrackedProduct extends TrackedProductsOfTheOrder {
  sellable_quantity: number;
  total_amount: number;
  quantity_purchased: number;
}

export interface PurchaseOrderProductsUpdates {
  purchaseOrderProductId: number;
  quantityPurchased: number;
  product_cost: string;
  profit: string;
}
