// Generated by https://quicktype.io

export interface DeleteOrderResponse {
  success: boolean;
  data: Data;
}

export interface Data {
  id: number;
  order_number: string;
  supplier_id: number;
  purchase_order_status_id: number;
  total_price: string;
  notes: string;
  is_active: boolean;
  updatedStatusAt: Date;
  createdAt: Date;
  updatedAt: Date;
}
