// Generated by https://quicktype.io

export interface GetSuppliersResponse {
  success: boolean;
  quantity: number;
  data: Supplier[];
}

export interface Supplier {
  id: number;
  supplier_name: string;
  createdAt: Date;
  updatedAt: Date;
}
